### ISSUE TITLE
May I use this source code? I would greatly appreciate your permission.

### ISSUE THREAD

**Issue by sosim13** [RYANFRANKLIN237/flutter-e-commerce-app#1]
Hello, I was working on program development but had to stop due to health issues, and now I'm planning to start an online store. 

While browsing GitHub, I came across your source code, and I really liked both the design and the variety of features. 

I wanted to ask if it would be okay to use your source code to create my online store. 

Since I'm a developer but not skilled in design, I would like to use most of the design as is, excluding the logo, 
and change only the logic for the payment module and currency conversion (from dollars to Korean won) during the purchase process. 

It would be a huge help if you allow me to use it.

**Comment by RYANFRANKLIN237** [comment]
Yes you can, that's what Github is for by the way.
